### ISSUE TITLE
[13.0] l10n_es_aeat_mod303_print issue with template

### ISSUE THREAD

**Issue by sergioeix** [sygel-technology/sy-l10n-spain#1]
Ubuntu 18.04 Odoo 13.0 Community
Steps to reproduce:
Install -> Calculate 303 model -> try to print

Error to render compiling AST
KeyError: 'type'
Template: l10n_es_aeat_mod303_print.report_aeat_mod303_document
Path: /t/t/div/div[3]/table[1]/tbody/tr[13]/td[2]/span
Node: <span t-field="o.type" data-oe-field-xpath="/t[1]/t[1]/div[1]/div[3]/table[1]/tbody[1]/tr[13]/td[2]/span[1]"/>

**Comment by ValentinVinagre** [comment]
Hi @sergioeix ,
True, the field 'type' in v13 is now 'statement_type'. https://github.com/sygel-technology/sy-l10n-spain/commit/725fd72ad771ac7ea8cea80df33d0ef5a26409ef
Can you try again?

**Comment by sergioeix** [comment]
Hi Valentin now works like a charm :)
